name: www2.ourverse.tf
on:
  push:
    branch: [development]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: pushing latest change on www2.ourverse.tf
        uses: appleboy/ssh-action@master
        with:
          host: www2.ourverse.tf
          username: webuser
          key: ${{ secrets.TF_SECRET }}
          port: 34022
          script: |
            cd websites/www_ourverse/
            git log -1
            git restore .
            git pull
            bash build.sh
