name: ourverse.tf
on:
  push:
    branch: [development]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: pushing latest change on www.ourverse.tf
        uses: appleboy/ssh-action@master
        with:
          host: www.ourverse.tf
          username: webuser
          key: ${{ secrets.TF_SECRET }}
          port: 34022
          script: |
            cd /home/webuser/websites/www_ourverse
            git log -1
            git restore static/css/index.css
            git pull
            bash build.sh
